### PR TITLE
Added Nebula starter theme

### PR DESCRIPTION
**Pull request by chrisblakley**
Adds the Nebula WordPress theme. Could use some documentation regarding what specifically the thumbprint array is looking for, but I've used something similar to the other frameworks.

### CODE REVIEW

**Comment by vovafeldman** [comment]
Yep, you are right, and we have added it:
image

**Comment by vovafeldman** [comment]
I actually [checked your code](https://github.com/chrisblakley/Nebula/blob/master/functions.php), and `class Nebula` is not in the `functions.php` file. Please fix the thumbprint based on the new description and I will merge.

**Comment by chrisblakley** [comment]
Thanks for the description- I've updated the thumbprint on my fork.

**Comment by vovafeldman** [comment]
@chrisblakley the framework is now listed on the site https://includewp.com/

The scraper didn't find any matching themes on .org. It could be one of the following:
1. The framework isn't used by any .org plugin / theme.
2. The framework is loaded using TGMPA (not yet recognized by IncludeWP).
3. Something wrong with the thumbprint. 

If you know there's a theme using it for sure, please share the URL so we can check why it wasn't recognized.

**Pull request merged**
