### PR TITLE
Adds Post Types Definitely and Options Definitely frameworks

### PR DESCRIPTION
**Pull request by felixarntz**
This PR adds two frameworks that I maintain: Post Types Definitely and Options Definitely which make scaffolding backend functionality and UI in WordPress easier.

### CODE REVIEW

**Comment by vovafeldman** [comment]
Hey @felixarntz, thanks for the PR. 
1. I checked the GitHub repos, and I think you have typos there because both of them do not exist.
2. With regards to the thumbprints, just to make sure, when plugin/theme is using your frameworks, if I check the given file + string, I'll find it there?

**Comment by felixarntz** [comment]
Oh my bad, I didn't provide my correct username 🙈
Regarding the thumbprints, these are correct.

I'll update the PR to have the right GitHub repos in it.

**Comment by felixarntz** [comment]
@vovafeldman: I updated the PR with the latest commit.

**Comment by vovafeldman** [comment]
@felixarntz the frameworks are now listed on the site https://includewp.com/

The scraper didn't find any matching plugins/themes on .org for the frameworks. It could be one of the following:
1. The framework isn't used by any .org plugin / theme.
2. The framework is loaded using TGMPA (not yet recognized by IncludeWP).
3. Something wrong with the thumbprint. 

If you know there's a plugin/theme using it for sure, please share the URL so we can check why it wasn't recognized.

**Comment by felixarntz** [comment]
It might just be that the library is not used by any, that's probably it.

**Pull request merged**
