### PR TITLE
Add Meta Box plugin

### PR DESCRIPTION
**Pull request by rilwis**
This PR adds the Meta Box plugin, a framework for developers to handle custom meta boxes and custom fields in WordPress.

### CODE REVIEW

**Comment by vovafeldman** [comment]
@rilwis Thanks for the PR! Can you please change the description to something like "Custom meta boxes and custom fields." It's obvious that this is a framework for developers ;)

**Comment by rilwis** [comment]
How does this sound “A custom meta boxes and custom fields toolset”?

**Comment by rilwis** [comment]
Just updated the description :)

**Comment by vovafeldman** [comment]
@rilwis the framework is now listed on the site:
https://includewp.com/
https://includewp.com/meta-box/

A tweet/share/like would be awesome ;)

**Comment by rilwis** [comment]
Thanks for your support. Just tweeted it: https://twitter.com/rilwis/status/770793233186119680

**Pull request merged**
