### PR TITLE
Added WP Customizer Utilities by ProteusThemes.

### PR DESCRIPTION
**Pull request by primozcigler**

### CODE REVIEW

**Comment by vovafeldman** [comment]
@primozcigler could you please try to add a thumbprint? We added a description of what it means:
image

**Comment by primozcigler** [comment]
Sure thing @vovafeldman, on it.

**Comment by primozcigler** [comment]
@vovafeldman done.

**Comment by vovafeldman** [comment]
@primozcigler the framework is now listed on the site https://includewp.com/

The scraper didn't find any matching plugins/themes on .org. It could be one of the following:
1. The framework isn't used by any .org plugin / theme.
2. The framework is loaded using TGMPA (not yet recognized by IncludeWP).
3. Something wrong with the thumbprint. 

If you know there's a plugin/theme using it for sure, please share the URL so we can check why it wasn't recognized.

**Pull request merged**
