### PR TITLE
Added Unyson framework

### PR DESCRIPTION
**Pull request by ghost**
- Added [Unyson framework](https://github.com/ThemeFuse/Unyson)
  
  staticshot_29-07-2016_17-33-59
- Fixed [PHP notices](https://github.com/Freemius/IncludeWP/blob/33eb6e0642dd41842a84ccc02646d04870879d98/includes/functions.php#L169) in cronjobs
- Enabled [update for frameworks](https://github.com/Freemius/IncludeWP/blob/33eb6e0642dd41842a84ccc02646d04870879d98/cronjobs/weekly-update.php#L5)
- Updated all frameworks information with `cronjobs/weekly-update.php` script

### CODE REVIEW

**Comment by vovafeldman** [comment]
@moldcraft thank you so much for spending the time to set it locally 👍  I'm glad you managed to do it. Having said that, could you please either clean the PR from all the compiled files or submit it as a new PR?

**Comment by moldcraft** [comment]
I will do, but I am curious why you can't accept it with compiled files?

**Comment by ghost** [comment]
@vovafeldman Done

**Comment by ghost** [comment]
silence is golden

**Comment by vovafeldman** [comment]
@moldcraft don't worry, I didn't forget about your PR. We will be merging all the submit frameworks soon (don't forget it's a side project and that we have a busy full time jobs). Appreciate your patience.

**Comment by vovafeldman** [comment]
Hey @moldcraft, I was checking your homepage and I'm trying to figure out if Unyson is a framework or actually a page builder for websites. Can you please help me out with the decision?

**Comment by ghost** [comment]
Unyson has:
1. [Option-types](http://manual.unyson.io/en/latest/options/introduction.html#content) (and the possibility to create your own) 
2. [Built-in](http://manual.unyson.io/en/latest/extension/introduction.html#content) **[Extensions](http://manual.unyson.io/en/latest/extensions/introduction.html#content)** (and the possibility to create your own)
3. [Helper functions](http://manual.unyson.io/en/latest/helpers/introduction.html#content)
4. [It integrates with theme](http://manual.unyson.io/en/latest/convention/directory-structure.html#content)

**Comment by ghost** [comment]
Here are the [themes made with Unyson](https://themeforest.net/search?utf8=%E2%9C%93&term=unyson&referrer=search&view=list&sort=sales)

**Comment by vovafeldman** [comment]
@moldcraft thanks! Final question, you mentioned that it's both for themes and plugins. If it's a drag & drop theme builder, why would I want to use it as a framework for my plugin? Do you have an example plugin that uses it?

**Comment by ghost** [comment]
I set plugins to false

**Comment by vovafeldman** [comment]
I manually added it https://github.com/Freemius/IncludeWP/blob/master/src/frameworks/unyson.php

And I have another question. Once a developer finish to build a theme with the plugin, what happens next? How this developer redistribute the theme? Does the theme require the plugin? Does the theme developer include the plugin in the theme's folder?

**Comment by ghost** [comment]
The theme requiers the plugin via TGM.

Thank you!

**Comment by vovafeldman** [comment]
@moldcraft the framework is now listed on the site https://includewp.com/

The scraper didn't find any matching plugins/themes on .org. It could be one of the following:
1. The framework isn't used by any .org plugin / theme.
2. The framework is loaded using TGMPA (not yet recognized by IncludeWP).
3. Something wrong with the thumbprint. 

If you know there's a plugin/theme using it for sure, please share the URL so we can check why it wasn't recognized.

**Comment by ghost** [comment]
Great! I don't know any theme on `wp.org` built with Unyson. Most of the themes are on [ThemeForest](https://themeforest.net/search?utf8=%E2%9C%93&term=unyson&referrer=search&view=list&sort=sales) and they require Unyson with TGM

**Pull request closed without merging**
