### PR TITLE
Add Beans Framework <beans.php>

### PR DESCRIPTION
**Pull request by thachpham92**
Hi Freemius,
I just add Beans framework for theme development. This framework is amazing, developer should take a look at it.

### CODE REVIEW

**Comment by vovafeldman** [comment]
@thachpham92 thanks for PR-ing! 
1. Is it a starter theme? If so, mention that. 
2. Could you please change the description to be short and descriptive (not a sales pitch). 
3. You're submission is missing the "thumbprint" params. It's a unique combination of a file name + a string that we should look in the WordPress.org themes repository, to automatically identify themes using beans.

**Comment by thachpham92** [comment]
Hello @vovafeldman,
Thanks for your feedback. First I would like to say I'm not own this theme, just a user.
1. This is a Theme Framework, not starter theme.
2. Yes, I will, sorry about that.
3. This framework is not existing in WordPress.org themes repository. So I couldn't use `thumbprint` params.

**Comment by vovafeldman** [comment]
It doesn't matter that the framework is not on wp.org, what matters is if themes on wp.org can use it. If that's  the case, we need the thumbprint to identify them.

**Comment by justintadlock** [comment]
Maybe I could be of some assistance here.  And, please correct me if I'm wrong on any part.

[Beans](http://www.getbeans.io/) seems to be a theme rather than a framework.  Therefore, other themes can't include it.

It's my understanding that the IncludeWP project is for actual frameworks and/or libraries that other themes/plugins can "include".  @vovafeldman, if this is the case, you might want to clarify what you mean by "framework" in the `readme.md` because many in the WP community use this term very loosely.  And, I suspect that you will get many theme submissions that aren't true frameworks.

**Comment by vovafeldman** [comment]
@justintadlock you are right! We are listing only frameworks/libs/sdks that other theme and plugin developers can include making development more efficient. I will add that note to the `readme.md` file.

**Pull request closed without merging**
