### PR TITLE
Codestar Framework

### PR DESCRIPTION
**Pull request by theperfectwill**
A superb **5 in 1, LIGHTweight, THEME & PLUGIN Options** Framework. :)

Hi. Thanks for this awesome idea/contribution. 

I'm not sure where the `'thumbprint'` ... `'file' => ' '` should be. Anything particular? I tried looking at some of the other Github only frameworks but not everything consistently lined up to files in their repo that I saw, so does this need to be the file from the website or something? I was wondering how the screenshot or image thumbnail was generated, if automatically. 

Thanks, Freemius.

### CODE REVIEW

**Comment by theperfectwill** [comment]
**Approval Reference Links:**

Website @ http://codestarframework.com/
Git @ http://codestarframework.com/codestar/
Docs @ http://codestarframework.com/documentation/
License @ http://codestarframework.com/license/

_Ping @Codestar_ ;) _(...Framework exposure help)_

**Comment by theperfectwill** [comment]
Added Cherry Framework, largely used by http://TemplatMonster.com.

@ http://www.cherryframework.com/
@ https://github.com/CherryFramework/CherryFramework 
_Ping @CherryFramework_

I believe the Cherry Framework is for plugins a too by looking some of their github extensions, but the site doesn't seem to share that specifically, so I left it out. If anyone knows, they can chip in.

**Comment by theperfectwill** [comment]
Added Boots Framework

@ http://wpboots.com/
@ https://github.com/wpboots/boots
_Ping @wpboots @kamalkhan_

Not sure if this ever came out of BETA, but the last update isn't too far out I think.

**Comment by vovafeldman** [comment]
@NoahjChampion the frameworks are now listed on the site https://includewp.com/

The scraper didn't find any matching plugins/themes on .org. It could be one of the following:
1. The framework isn't used by any .org plugin / theme.
2. The framework is loaded using TGMPA (not yet recognized by IncludeWP).
3. Something wrong with the thumbprint. 

If you know there's a plugin/theme using it for sure, please share the URL so we can check why it wasn't recognized.

**Comment by theperfectwill** [comment]
@vovafeldman 

Ok, thanks. An author recently said that Wordpress isn;t allowing any Theme Option based themes, only Customizer integrated themes. I can't confirm that but that is what one author said a couple weeks about concerning using Codestar. Other than that, I'm not sure there are any .ORG themes using Codestar. But I can ask. There are premium themes using this framework. 

What do you think about having an option to enter manually themes using the framework? Especially if Wordpress isn't allowing Theme Option based themes? Thoughts?
- Thanks appreciate it! #Salute

**Pull request merged**
