### PR TITLE
Adds ButterBean and Hybrid Core frameworks

### PR DESCRIPTION
**Pull request by justintadlock**
This adds the two frameworks that I manage: ButterBean and Hybrid Core.

### CODE REVIEW

**Comment by vovafeldman** [comment]
Thanks for PR-ing! For the hybrid framework, could you please come up with a descriptive description. It should be a short one liner that will help developers to understand what's in the box. Though I'd love to have themes with superpowers :)

**Comment by justintadlock** [comment]
I thought about "Does a lot of cool sh*t", but figured that might not be appropriate. :)

I'll think on it. Maybe something along the lines of "Theme development toolbox."

**Comment by vovafeldman** [comment]
@justintadlock "Theme development toolbox." is good. Please update, and I'll merge.

**Comment by vovafeldman** [comment]
@justintadlock the frameworks are now listed on the site https://includewp.com/

Here's the Hybrid page: https://includewp.com/hybrid-core/#focus

The scraper didn't find any matching plugins/themes on .org for **ButterBen**. It could be one of the following:
1. The framework isn't used by any .org plugin / theme.
2. The framework is loaded using TGMPA (not yet recognized by IncludeWP).
3. Something wrong with the thumbprint. 

If you know there's a plugin/theme using it for sure, please share the URL so we can check why it wasn't recognized.

**Comment by justintadlock** [comment]
ButterBean 1.0 actually just got officially released today.  I'll have a plugin in the repo that uses it before the end of the week.

**Pull request merged**
