### PR TITLE
Adding WordPress Plugin Template

### PR DESCRIPTION
**Pull request by hlashbrooke**
I'm not 100% sure what the `thumbprint` parameter is for, so I left that out.

### CODE REVIEW

**Comment by vovafeldman** [comment]
image

**Comment by hlashbrooke** [comment]
Gotcha, then I don't need the `thumbprint` parameter for this framework. This PR is complete then.

**Comment by vovafeldman** [comment]
@hlashbrooke the framework is now listed on the site https://includewp.com/

**Comment by hlashbrooke** [comment]
@vovafeldman Thanks!

**Pull request merged**
